### ISSUE TITLE
Negative numbers are being transfered

### ISSUE THREAD

**Issue by crosby0320** [bradtaniguchi/GoTorosBank#20]
So like I can make a transfer from checkings to my savings and IDK what that does in the back end it may subtract from my money but all we have to do it check it in the front end so that it won't happen again.

**Comment by bradtaniguchi** [comment]
Somewhat "fixed" as of this [commit](https://github.com/bradtaniguchi/GoTorosBank/commit/8763edb32040143a3c686499b3b3e8022384a8f5)
Now we only get the number, and remove any other non-characters. This includes a - character. So If you input -25, the system takes it in as just 25. 
This may get updated later in the future, but due to time, this makeshift fix will be left.
